package vista;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import javax.swing.*;

import controlador.Coordinador;

/**
 *
 * @author User
 */

public class VentanaPrincipal extends JFrame implements ActionListener {
	  private javax.swing.JButton botonConsultaIndividual;
	  private javax.swing.JButton botonRegistrar;
	  private javax.swing.JButton botonConsultaTabla;
	  private javax.swing.JLabel labelTitulo,labelInferior;
	  private javax.swing.JPanel miPanelPrincipal,panelTitulo,panelInferior;
	  private JMenuBar barraMenu;
	  private JMenu menu;
	  private JMenuItem itemOpciones;
	  private Dimension tamPantalla;
	  private Rectangle pantalla;
	  private Coordinador miCoordinador;
      private int tipoUsuario = 0;
      private String usuarioDocumento;


    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setTitle("Ventana Principal");
        setSize(650, 350);
        setLocationRelativeTo(null);
        tamPantalla=Toolkit.getDefaultToolkit().getScreenSize();
        pantalla= new Rectangle(tamPantalla);
        setBounds(pantalla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        miPanelPrincipal = new JPanel(new GridBagLayout());
        panelTitulo = new JPanel(new BorderLayout());
        panelInferior = new JPanel(new FlowLayout(FlowLayout.RIGHT));

        labelTitulo = new JLabel("Bienvenido al Sistema", SwingConstants.CENTER);
        labelInferior = new JLabel("http://codejavu.blogspot.com", SwingConstants.CENTER);

        botonConsultaIndividual = new JButton("CONSULTA USUARIO INDIVIDUAL");
        botonRegistrar = new JButton("REGISTRAR");
        botonConsultaTabla = new JButton("TABLA DE USUARIOS");

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        labelTitulo.setFont(new Font("Chiller", Font.PLAIN, 48));
        labelTitulo.setForeground(Color.WHITE);
        panelTitulo.setBackground(Color.BLACK);
        panelTitulo.add(labelTitulo, BorderLayout.CENTER);

        labelInferior.setFont(new Font("Chiller", Font.PLAIN, 30));
        labelInferior.setForeground(Color.WHITE);
        panelInferior.setBackground(Color.BLACK);
        panelInferior.add(labelInferior);

        botonConsultaIndividual.setFont(new Font("Tahoma", Font.PLAIN, 24));
        botonRegistrar.setFont(new Font("Tahoma", Font.PLAIN, 24));
        botonConsultaTabla.setFont(new Font("Tahoma", Font.PLAIN, 24));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 0, 10, 0);
        gbc.gridx = 0;
        gbc.anchor = GridBagConstraints.CENTER;

        gbc.gridy = 0;
        miPanelPrincipal.add(botonRegistrar, gbc);

        gbc.gridy = 1;
        miPanelPrincipal.add(botonConsultaIndividual, gbc);

        gbc.gridy = 2;
        miPanelPrincipal.add(botonConsultaTabla, gbc);

        barraMenu = new JMenuBar();
        menu = new JMenu("Opciones");
        itemOpciones = new JMenuItem("Cambiar de Usuario");
        menu.add(itemOpciones);
        barraMenu.add(menu);
        setJMenuBar(barraMenu);

        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(panelTitulo, BorderLayout.NORTH);
        getContentPane().add(miPanelPrincipal, BorderLayout.CENTER);
        getContentPane().add(panelInferior, BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);

        botonConsultaIndividual.addActionListener(this);
        botonRegistrar.addActionListener(this);
        itemOpciones.addActionListener(this);
        botonConsultaTabla.addActionListener(this);

    }

	public void asignarPrivilegios(ArrayList<String> usuario) {
        this.usuarioDocumento = usuario.getLast();
		labelTitulo.setText("Bienvenido : "+usuario.getFirst());

		if (usuario.getFirst().equals("Administrador")) {
            this.tipoUsuario = 1;
		}else if(usuario.getFirst().equals("Usuario")) {
            this.tipoUsuario = 2;
		} else if (usuario.getFirst().equals("Secretaria")) {
            this.tipoUsuario = 3;

        }

	}

	@Override
	public void actionPerformed(ActionEvent e) {
		if (e.getSource()==itemOpciones) {
			miCoordinador.mostrarLogin();
		}

		if (e.getSource()==botonRegistrar) {
			miCoordinador.mostrarVentanaRegistro();
		}

		if (e.getSource()==botonConsultaIndividual) {
            miCoordinador.setUsuarioDocumento(usuarioDocumento);
            miCoordinador.setUsuarioTipo(tipoUsuario);
			miCoordinador.mostrarVentanaConsulta();
		}

        if(e.getSource()==botonConsultaTabla) {
            miCoordinador.setUsuarioDocumento(usuarioDocumento);
            miCoordinador.setUsuarioTipo(tipoUsuario);
            miCoordinador.mostrarVentanaTabla();
        }
	}

    public void setCoordinador(Coordinador miCoordinador) {
        this.miCoordinador = miCoordinador;
    }


}
